cache:
  CACHE_TYPE: simple
jwt:
  SALT: thss
  EXPIRY: 72  # HOURS
app:
  ENCRY_SALT: cheaple
  ENV: development
  SECRET: 2018cheaple011660
  HOST: localhost
  PORT: 5000
db:
  MYSQL: sqlite:///newborn.db